.PHONY: clean All

All:
	@echo "----------Building project:[ lib_test - Debug ]----------"
	@cd "lib_test" && "$(MAKE)" -f  "lib_test.mk" && "$(MAKE)" -f  "lib_test.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ lib_test - Debug ]----------"
	@cd "lib_test" && "$(MAKE)" -f  "lib_test.mk" clean
