.PHONY: clean All

All:
	@echo "----------Building project:[ 3bolltest - Debug ]----------"
	@cd "3bolltest" && "$(MAKE)" -f  "3bolltest.mk" && "$(MAKE)" -f  "3bolltest.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ 3bolltest - Debug ]----------"
	@cd "3bolltest" && "$(MAKE)" -f  "3bolltest.mk" clean
