.PHONY: clean All

All:
	@echo "----------Building project:[ spel - Debug ]----------"
	@cd "spel" && "$(MAKE)" -f  "spel.mk" && "$(MAKE)" -f  "spel.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ spel - Debug ]----------"
	@cd "spel" && "$(MAKE)" -f  "spel.mk" clean
